version: "3.9"

services:
  backend:
    build: .
    container_name: lista-precios-backend
    image: lista-precios-backend
    ports:
      - "3001:3001"
    env_file:
      - .env
    restart: always